title: Programming for fun and profit
description: "Programming for fun and profit"
author:
  name: "zygygy"
  email: "zygygy@outlook.com"
  url: "https://zygygy.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "zygygy"
year : "2018"

# Google Analytics
google_analytics: UA-132465883-1
